#!/bin/sh

src_file=$1

if [ "$src_file" == "" ]; then 
    echo "this command is particular for scp files to fanyizhong's host"
    echo "and now you need a src file path."
else
    scp -r $src_file fanyizhong@cq01-rdqa-dev015.cq01.baidu.com:/home/users/fanyizhong/code
fi
